### ISSUE TITLE
Drop support for Python 2.7 & Python 3.4

### ISSUE THREAD

**Issue by gurpreetatwal** [smartcar/python-sdk#74]
Python 2.7 will no longer be supported after January 1st, 2020 [1] and Python 3.4 has been unsupported since March of this year. [2] 

\[1]: https://devguide.python.org/#status-of-python-branches
\[2]: https://www.python.org/dev/peps/pep-0429/#release-schedule
\[3]: https://en.wikipedia.org/wiki/History_of_Python

**Comment by dbartenstein** [comment]
Would be nice if you started using type hints: https://docs.python.org/3/library/typing.html
