### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by adamchainz** [smartcar/python-sdk#81]
Please keep a changelog summarizing user-facing issues so upgrades are easy to understand: https://keepachangelog.com/en/1.0.0/

Thanks :)

**Comment by gurpreetatwal** [comment]
Done! Thanks for bringing this up. Our plan is to have changelogs across all of our SDKs, slowly slowly getting there haha

**Comment by adamchainz** [comment]
Thanks for the fast turnaround!
